#!/bin/bash

FIPID="502d8bc7-8807-47cb-9e1a-ffc0373095ba"
FLAVOR="m1.tiny-prod"
IMAGEID="5db66a8a-3165-4606-982d-43e89846c16f"
#NETIDEXT="37afe95c-34de-41ba-a9b6-a3dd1f5dac7e"
NETIDINT=""
# USERDATA="keppalivetest.cmd"

PORTID=$(neutron port-create ${NETID} | grep " id " | awk '{print $4}')

neutron floatingip-associate $FIPID $PORTID


if [ -n "${USERDATA}" ]
then
OPTIONS="--user-data ${USERDATA} "
fi

nova boot --image $IMAGEID \
          --flavor $FLAVOR \
          --security-groups default \
          --availability-zone nova \
          $OPTIONS \
          --key-name foucault \
          --nic port-id=${PORTID} \
          scalr
          




#neutron floatingip-disassociate $FIPID
#          --user-data docker-node.cmd \
